/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java7_nhom_3;

import entities.Employee;
import entities.Price;
import entities.Ticket;
import entities.Vehicle;
import entities.Vehicle_Parking;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author LA
 */
public class Frame_StaffWork extends javax.swing.JFrame {

    Employee employee;
    Vehicle_Parking vehicleParkingCheckOut;
    /**
     * Creates new form Frame_StaffWork
     */
    public Frame_StaffWork() {
        initComponents();
    }

    public Frame_StaffWork(Employee emp) {
        initComponents();
        System.out.println(emp);
        this.employee = emp;

        jLabel_parkingLotID.setText(employee.getParkingLotID());
        jLabel_staffName.setText(employee.getName());
        jRadioButton_in_motorbike.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_in_vehicleType = new javax.swing.ButtonGroup();
        buttonGroup_out_vehicleType = new javax.swing.ButtonGroup();
        jDialog_CheckOut = new javax.swing.JDialog();
        jButton_checkOut = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel_checkOut_licenesPlate = new javax.swing.JLabel();
        jLabel_checkOut_ticket = new javax.swing.JLabel();
        jLabel_checkOut_timeIn = new javax.swing.JLabel();
        jLabel_checkOut_ParkingFee = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_in = new javax.swing.JButton();
        btn_out = new javax.swing.JButton();
        jPanel_container = new javax.swing.JPanel();
        jPanel_in = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_in_licensePlate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_in_ticketNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox_priority = new javax.swing.JCheckBox();
        jButton_checkIn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton_in_motorbike = new javax.swing.JRadioButton();
        jRadioButton_in_bikecycle = new javax.swing.JRadioButton();
        jRadioButton_in_car = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel_parkingLotID = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_staffName = new javax.swing.JLabel();
        jLabel_in_licensePlateMsg = new javax.swing.JLabel();
        jLabel_in_ticketMsg = new javax.swing.JLabel();
        jPanel_out = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_out_licensePlate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_out_ticketNumber = new javax.swing.JTextField();
        jButton_check = new javax.swing.JButton();
        jLabel_out_licenseMsg = new javax.swing.JLabel();
        jLabel_out_tiketMsg = new javax.swing.JLabel();

        jDialog_CheckOut.setModal(true);
        jDialog_CheckOut.setSize(new java.awt.Dimension(400, 300));

        jButton_checkOut.setText("Check out");
        jButton_checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_checkOutActionPerformed(evt);
            }
        });

        jButton_cancel.setText("Cancel");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        jLabel2.setText("Licenes plate:");

        jLabel9.setText("Ticket:");

        jLabel13.setText("Time in");

        jLabel15.setText("Parking fee:");

        jLabel_checkOut_licenesPlate.setText("jLabel16");

        jLabel_checkOut_ticket.setText("jLabel17");

        jLabel_checkOut_timeIn.setText("jLabel18");

        jLabel_checkOut_ParkingFee.setText("jLabel20");

        javax.swing.GroupLayout jDialog_CheckOutLayout = new javax.swing.GroupLayout(jDialog_CheckOut.getContentPane());
        jDialog_CheckOut.getContentPane().setLayout(jDialog_CheckOutLayout);
        jDialog_CheckOutLayout.setHorizontalGroup(
            jDialog_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_CheckOutLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jDialog_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_checkOut, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addGroup(jDialog_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addGroup(jDialog_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_CheckOutLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jDialog_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_checkOut_timeIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_checkOut_licenesPlate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_checkOut_ticket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_checkOut_ParkingFee, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(jDialog_CheckOutLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jDialog_CheckOutLayout.setVerticalGroup(
            jDialog_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_CheckOutLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jDialog_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_checkOut_licenesPlate))
                .addGap(18, 18, 18)
                .addGroup(jDialog_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel_checkOut_ticket))
                .addGap(18, 18, 18)
                .addGroup(jDialog_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel_checkOut_timeIn))
                .addGap(18, 18, 18)
                .addGroup(jDialog_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel_checkOut_ParkingFee))
                .addGap(32, 32, 32)
                .addGroup(jDialog_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_checkOut)
                    .addComponent(jButton_cancel))
                .addGap(37, 37, 37))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btn_in.setText("ENTRANCE");
        btn_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inActionPerformed(evt);
            }
        });

        btn_out.setText("EXIT");
        btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_in, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_out, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_in)
                    .addComponent(btn_out))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel_container.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ENTRANCE GATE");

        jLabel3.setText("License plate");

        jLabel4.setText("Ticket number");

        jLabel5.setText("School staff");

        jButton_checkIn.setText("CHECK IN");
        jButton_checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_checkInActionPerformed(evt);
            }
        });

        jLabel10.setText("Vehicle");

        buttonGroup_in_vehicleType.add(jRadioButton_in_motorbike);
        jRadioButton_in_motorbike.setText("Motorbike");

        buttonGroup_in_vehicleType.add(jRadioButton_in_bikecycle);
        jRadioButton_in_bikecycle.setText("Bikecycle");
        jRadioButton_in_bikecycle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_in_bikecycleStateChanged(evt);
            }
        });
        jRadioButton_in_bikecycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_in_bikecycleActionPerformed(evt);
            }
        });

        buttonGroup_in_vehicleType.add(jRadioButton_in_car);
        jRadioButton_in_car.setText("Car");

        jLabel11.setText("Parking lot : ");

        jLabel12.setText("Staff : ");

        jLabel_in_licensePlateMsg.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_in_licensePlateMsg.setText("jLabel13");

        jLabel_in_ticketMsg.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_in_ticketMsg.setText("jLabel13");

        javax.swing.GroupLayout jPanel_inLayout = new javax.swing.GroupLayout(jPanel_in);
        jPanel_in.setLayout(jPanel_inLayout);
        jPanel_inLayout.setHorizontalGroup(
            jPanel_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_inLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_priority, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_checkIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_inLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_parkingLotID, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_staffName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_inLayout.createSequentialGroup()
                        .addGroup(jPanel_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_in_licensePlateMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_inLayout.createSequentialGroup()
                                .addComponent(jRadioButton_in_motorbike, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_in_bikecycle, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_in_car, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_in_licensePlate)))
                    .addGroup(jPanel_inLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_in_ticketMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_in_ticketNumber))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel_inLayout.setVerticalGroup(
            jPanel_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel_parkingLotID)
                    .addComponent(jLabel12)
                    .addComponent(jLabel_staffName))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jRadioButton_in_motorbike)
                    .addComponent(jRadioButton_in_bikecycle)
                    .addComponent(jRadioButton_in_car))
                .addGap(18, 18, 18)
                .addGroup(jPanel_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_in_licensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addComponent(jLabel_in_licensePlateMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_in_ticketNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_in_ticketMsg)
                .addGap(18, 18, 18)
                .addGroup(jPanel_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBox_priority))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton_checkIn)
                .addGap(35, 35, 35))
        );

        jPanel_container.add(jPanel_in, "card2");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("EXIT GATE");

        jLabel7.setText("License plate");

        jLabel8.setText("Ticket number");

        jButton_check.setText("CHECK");
        jButton_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_checkActionPerformed(evt);
            }
        });

        jLabel_out_licenseMsg.setText("jLabel14");

        jLabel_out_tiketMsg.setText("jLabel14");

        javax.swing.GroupLayout jPanel_outLayout = new javax.swing.GroupLayout(jPanel_out);
        jPanel_out.setLayout(jPanel_outLayout);
        jPanel_outLayout.setHorizontalGroup(
            jPanel_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_outLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_check, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_outLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_out_licenseMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_out_licensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_outLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_out_tiketMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_out_ticketNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel_outLayout.setVerticalGroup(
            jPanel_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_outLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(56, 56, 56)
                .addGroup(jPanel_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_out_licensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_out_licenseMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_out_ticketNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_out_tiketMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton_check)
                .addGap(75, 75, 75))
        );

        jPanel_container.add(jPanel_out, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inActionPerformed
        // TODO add your handling code here:
        jPanel_in.setVisible(true);
        jPanel_out.setVisible(false);

    }//GEN-LAST:event_btn_inActionPerformed

    private void btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outActionPerformed
        // TODO add your handling code here:
        jPanel_in.setVisible(false);
        jPanel_out.setVisible(true);
    }//GEN-LAST:event_btn_outActionPerformed

    private void jButton_checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checkInActionPerformed
        // TODO add your handling code here:

        String parkingLotID;
        String ticketNum;
        String licensePlate;
        Vehicle vehicleType = null;
        String timeIn;
        String timeOut = "";
        boolean priority;

        if (jRadioButton_in_bikecycle.isSelected()) {
            vehicleType = Vehicle.BIKECYCLE;
        }
        if (jRadioButton_in_motorbike.isSelected()) {
            vehicleType = Vehicle.MOTORBIKE;
        }
        if (jRadioButton_in_car.isSelected()) {
            vehicleType = Vehicle.CAR;
        }

        parkingLotID = employee.getParkingLotID();
        ticketNum = jTextField_in_ticketNumber.getText().trim();
        licensePlate = jTextField_in_licensePlate.getText().trim();
        timeIn = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy/MM/dd - HH:mm:ss"));
        priority = jCheckBox_priority.isSelected();

        //validate
        jLabel_in_licensePlateMsg.setText("");
        jLabel_in_ticketMsg.setText("");

        boolean isValid = true;
        String requiredFieldMsg = "This is a required field";
        if (licensePlate.isEmpty() && vehicleType != Vehicle.BIKECYCLE) {
            isValid = false;
            jLabel_in_licensePlateMsg.setText(requiredFieldMsg);
        }

        if (ticketNum.isEmpty()) {
            isValid = false;
            jLabel_in_ticketMsg.setText(requiredFieldMsg);
        }

        if (isValid == false) {
            return;
        }

        try {
            Set<Ticket> tickets = dataAccess.TicketDataAccess.getTickets();
            Map<String, Vehicle_Parking> vehicle_parkings = dataAccess.Vehicle_ParkingDataAccess.getVehicles();
            if (!tickets.contains(new Ticket(ticketNum))) {
                JOptionPane.showMessageDialog(this, "This ticket is not exists");
                return;
            }

            if (vehicle_parkings.containsKey(ticketNum)) {
                JOptionPane.showMessageDialog(this, "This ticket is not available");
                return;
            }
        } catch (IOException ex) {
            Logger.getLogger(Frame_StaffWork.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Frame_StaffWork.class.getName()).log(Level.SEVERE, null, ex);
        }

        //end validate
        Vehicle_Parking v = new Vehicle_Parking(
                parkingLotID,
                 ticketNum,
                 licensePlate,
                 vehicleType,
                 timeIn,
                 timeOut,
                 priority);
        try {
            dataAccess.Vehicle_ParkingDataAccess.addVehicle(v);
        } catch (IOException ex) {
            Logger.getLogger(Frame_StaffWork.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(v.toString());

    }//GEN-LAST:event_jButton_checkInActionPerformed

    private void jRadioButton_in_bikecycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_in_bikecycleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_in_bikecycleActionPerformed

    private void jRadioButton_in_bikecycleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_in_bikecycleStateChanged
        // TODO add your handling code here:
        boolean isSelected = jRadioButton_in_bikecycle.isSelected();
        jTextField_in_licensePlate.setEnabled(!isSelected);
        if (isSelected) {
            jTextField_in_licensePlate.setText("");
        }
    }//GEN-LAST:event_jRadioButton_in_bikecycleStateChanged

    private void jButton_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checkActionPerformed
        // TODO add your handling code here:
        Map<String, Vehicle_Parking> vehicles = new TreeMap<>();
        try {
            vehicles = dataAccess.Vehicle_ParkingDataAccess.getVehicles();
        } catch (Exception ex) {
            Logger.getLogger(Frame_StaffWork.class.getName()).log(Level.SEVERE, null, ex);
        }
        String ticket = jTextField_out_ticketNumber.getText().trim();
        String licensePlate = jTextField_out_licensePlate.getText().trim();
        Vehicle_Parking v = vehicles.get(ticket);
        if (v == null) {
            JOptionPane.showMessageDialog(this, "No infor");
            return;
        } else {
            v.setTimeOut(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy/MM/dd - HH:mm:ss")));
            vehicleParkingCheckOut = v;
            if (v.getLicensePlate().compareTo(licensePlate) != 0) {
                JOptionPane.showMessageDialog(this, "Not match");
                return;
            }
        }
        System.out.println(v.toString());

        jLabel_checkOut_licenesPlate.setText(v.getLicensePlate());
        jLabel_checkOut_ticket.setText(v.getTicket());
        jLabel_checkOut_timeIn.setText(v.getTimeIn());

        int parkingFee;

        switch (v.getType()) {
            case BIKECYCLE:
                parkingFee = Price.BIKECYCLE.getPrice();
                break;
            case MOTORBIKE:
                parkingFee = Price.MOTORBIKE.getPrice();
                break;
            case CAR:
                parkingFee = Price.CAR.getPrice();
                break;
            default:
                throw new AssertionError();
        }
        jLabel_checkOut_ParkingFee.setText("" + parkingFee);

        jDialog_CheckOut.setVisible(true);
        System.out.println(parkingFee);

    }//GEN-LAST:event_jButton_checkActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        // TODO add your handling code here:
        jDialog_CheckOut.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jButton_checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checkOutActionPerformed
        try {
            // TODO add your handling code here:
            dataAccess.Vehicle_ParkingDataAccess.removeVehicle(jLabel_checkOut_ticket.getText());
            dataAccess.LogDataAccess.add(vehicleParkingCheckOut);
            jTextField_out_licensePlate.setText("");
            jTextField_out_ticketNumber.setText("");
            jDialog_CheckOut.dispose();
        } catch (IOException ex) {
            Logger.getLogger(Frame_StaffWork.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Frame_StaffWork.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_checkOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_StaffWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_StaffWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_StaffWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_StaffWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_StaffWork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_in;
    private javax.swing.JButton btn_out;
    private javax.swing.ButtonGroup buttonGroup_in_vehicleType;
    private javax.swing.ButtonGroup buttonGroup_out_vehicleType;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_check;
    private javax.swing.JButton jButton_checkIn;
    private javax.swing.JButton jButton_checkOut;
    private javax.swing.JCheckBox jCheckBox_priority;
    private javax.swing.JDialog jDialog_CheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_checkOut_ParkingFee;
    private javax.swing.JLabel jLabel_checkOut_licenesPlate;
    private javax.swing.JLabel jLabel_checkOut_ticket;
    private javax.swing.JLabel jLabel_checkOut_timeIn;
    private javax.swing.JLabel jLabel_in_licensePlateMsg;
    private javax.swing.JLabel jLabel_in_ticketMsg;
    private javax.swing.JLabel jLabel_out_licenseMsg;
    private javax.swing.JLabel jLabel_out_tiketMsg;
    private javax.swing.JLabel jLabel_parkingLotID;
    private javax.swing.JLabel jLabel_staffName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_container;
    private javax.swing.JPanel jPanel_in;
    private javax.swing.JPanel jPanel_out;
    private javax.swing.JRadioButton jRadioButton_in_bikecycle;
    private javax.swing.JRadioButton jRadioButton_in_car;
    private javax.swing.JRadioButton jRadioButton_in_motorbike;
    private javax.swing.JTextField jTextField_in_licensePlate;
    private javax.swing.JTextField jTextField_in_ticketNumber;
    private javax.swing.JTextField jTextField_out_licensePlate;
    private javax.swing.JTextField jTextField_out_ticketNumber;
    // End of variables declaration//GEN-END:variables
}
