/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

import dataAccess.VehicleDataAccess;
import entities.Employee;
import entities.UnitPrice;
import entities.Ticket;
import entities.VehicleType;
import entities.LoggedVehicle;
import entities.Vehicle;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author LA
 */
public class Frame_StaffWork extends javax.swing.JFrame {

    Employee employee;
    Vehicle  vehicleParkingCheckOut;
    /**
     * Creates new form Frame_StaffWork
     */
    public Frame_StaffWork() {
        initComponents();
    }

    public Frame_StaffWork(Employee emp) {
        initComponents();
        System.out.println(emp);
        this.employee = emp;

        jLabel_parkingLotID.setText(employee.getParkingLotID());
        jLabel_staffName.setText(employee.getName());
        jRadioButton_in_motorbike.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	// Generated using JFormDesigner Evaluation license - Trường Khắc Nguyễn
	private void initComponents() {
		jPanel1 = new JPanel();
		btn_in = new JButton();
		btn_out = new JButton();
		jPanel_container = new JPanel();
		jPanel_in = new JPanel();
		jLabel1 = new JLabel();
		jTextField_in_licensePlate = new JTextField();
		jLabel3 = new JLabel();
		jTextField_in_ticketNumber = new JTextField();
		jLabel4 = new JLabel();
		jLabel5 = new JLabel();
		jCheckBox_priority = new JCheckBox();
		jButton_checkIn = new JButton();
		jLabel10 = new JLabel();
		jRadioButton_in_motorbike = new JRadioButton();
		jRadioButton_in_bikecycle = new JRadioButton();
		jRadioButton_in_car = new JRadioButton();
		jLabel11 = new JLabel();
		jLabel_parkingLotID = new JLabel();
		jLabel12 = new JLabel();
		jLabel_staffName = new JLabel();
		jLabel_in_licensePlateMsg = new JLabel();
		jLabel_in_ticketMsg = new JLabel();
		jPanel_out = new JPanel();
		jLabel6 = new JLabel();
		jLabel7 = new JLabel();
		jTextField_out_licensePlate = new JTextField();
		jLabel8 = new JLabel();
		jTextField_out_ticketNumber = new JTextField();
		jButton_check = new JButton();
		jLabel_out_licenseMsg = new JLabel();
		jLabel_out_tiketMsg = new JLabel();
		jDialog_CheckOut = new JDialog();
		jButton_checkOut = new JButton();
		jButton_cancel = new JButton();
		jLabel2 = new JLabel();
		jLabel9 = new JLabel();
		jLabel13 = new JLabel();
		jLabel15 = new JLabel();
		jLabel_checkOut_licenesPlate = new JLabel();
		jLabel_checkOut_ticket = new JLabel();
		jLabel_checkOut_timeIn = new JLabel();
		jLabel_checkOut_ParkingFee = new JLabel();
		buttonGroup_in_vehicleType = new ButtonGroup();

		//======== this ========
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		var contentPane = getContentPane();

		//======== jPanel1 ========
		{
			jPanel1.setBackground(new Color(0xcccccc));
			jPanel1.setBorder ( new javax . swing. border .CompoundBorder ( new javax . swing. border .TitledBorder ( new javax . swing. border
			.EmptyBorder ( 0, 0 ,0 , 0) ,  "JF\u006frmDesi\u0067ner Ev\u0061luatio\u006e" , javax. swing .border . TitledBorder. CENTER ,javax
			. swing. border .TitledBorder . BOTTOM, new java. awt .Font ( "Dialo\u0067", java .awt . Font. BOLD ,
			12 ) ,java . awt. Color .red ) ,jPanel1. getBorder () ) ); jPanel1. addPropertyChangeListener(
				e -> { if( "borde\u0072".equals (e.
				getPropertyName () ) )throw new RuntimeException( ) ;});

			//---- btn_in ----
			btn_in.setText("ENTRANCE");
			btn_in.addActionListener(e -> btn_inActionPerformed(e));

			//---- btn_out ----
			btn_out.setText("EXIT");
			btn_out.addActionListener(e -> btn_outActionPerformed(e));

			GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
			jPanel1.setLayout(jPanel1Layout);
			jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup()
					.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(btn_in, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btn_out, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
			);
			jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup()
					.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(14, 14, 14)
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
							.addComponent(btn_in)
							.addComponent(btn_out))
						.addContainerGap(17, Short.MAX_VALUE))
			);
		}

		//======== jPanel_container ========
		{
			jPanel_container.setLayout(new CardLayout());

			//======== jPanel_in ========
			{

				//---- jLabel1 ----
				jLabel1.setFont(new Font("Segoe UI", Font.PLAIN, 18));
				jLabel1.setText("ENTRANCE GATE");

				//---- jLabel3 ----
				jLabel3.setText("License plate");

				//---- jLabel4 ----
				jLabel4.setText("Ticket number");

				//---- jLabel5 ----
				jLabel5.setText("School staff");

				//---- jButton_checkIn ----
				jButton_checkIn.setText("CHECK IN");
				jButton_checkIn.addActionListener(e -> jButton_checkInActionPerformed(e));

				//---- jLabel10 ----
				jLabel10.setText("Vehicle");

				//---- jRadioButton_in_motorbike ----
				jRadioButton_in_motorbike.setText("Motorbike");

				//---- jRadioButton_in_bikecycle ----
				jRadioButton_in_bikecycle.setText("Bikecycle");
				jRadioButton_in_bikecycle.addChangeListener(e -> jRadioButton_in_bikecycleStateChanged(e));
				jRadioButton_in_bikecycle.addActionListener(e -> jRadioButton_in_bikecycleActionPerformed(e));

				//---- jRadioButton_in_car ----
				jRadioButton_in_car.setText("Car");

				//---- jLabel11 ----
				jLabel11.setText("Parking lot : ");

				//---- jLabel12 ----
				jLabel12.setText("Staff : ");

				//---- jLabel_in_licensePlateMsg ----
				jLabel_in_licensePlateMsg.setForeground(Color.red);
				jLabel_in_licensePlateMsg.setText("jLabel13");

				//---- jLabel_in_ticketMsg ----
				jLabel_in_ticketMsg.setForeground(Color.red);
				jLabel_in_ticketMsg.setText("jLabel13");

				GroupLayout jPanel_inLayout = new GroupLayout(jPanel_in);
				jPanel_in.setLayout(jPanel_inLayout);
				jPanel_inLayout.setHorizontalGroup(
					jPanel_inLayout.createParallelGroup()
						.addGroup(jPanel_inLayout.createSequentialGroup()
							.addGap(24, 24, 24)
							.addGroup(jPanel_inLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel_in_ticketMsg, GroupLayout.PREFERRED_SIZE, 306, GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel_inLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
									.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 294, GroupLayout.PREFERRED_SIZE)
									.addComponent(jButton_checkIn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addGroup(jPanel_inLayout.createSequentialGroup()
										.addComponent(jLabel11)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel_parkingLotID, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
										.addGap(30, 30, 30)
										.addComponent(jLabel12)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel_staffName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
									.addGroup(jPanel_inLayout.createSequentialGroup()
										.addGroup(jPanel_inLayout.createParallelGroup()
											.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
											.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel_inLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
											.addComponent(jLabel_in_licensePlateMsg, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
											.addGroup(jPanel_inLayout.createSequentialGroup()
												.addComponent(jRadioButton_in_motorbike, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jRadioButton_in_bikecycle, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jRadioButton_in_car, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE))
											.addComponent(jTextField_in_licensePlate)))
									.addGroup(jPanel_inLayout.createSequentialGroup()
										.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jTextField_in_ticketNumber))
									.addGroup(jPanel_inLayout.createSequentialGroup()
										.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jCheckBox_priority, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE))))
							.addContainerGap(29, Short.MAX_VALUE))
				);
				jPanel_inLayout.setVerticalGroup(
					jPanel_inLayout.createParallelGroup()
						.addGroup(jPanel_inLayout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel_inLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel11)
								.addComponent(jLabel_parkingLotID)
								.addComponent(jLabel12)
								.addComponent(jLabel_staffName))
							.addGap(18, 18, 18)
							.addComponent(jLabel1)
							.addGap(13, 13, 13)
							.addGroup(jPanel_inLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel10)
								.addComponent(jRadioButton_in_motorbike)
								.addComponent(jRadioButton_in_bikecycle)
								.addComponent(jRadioButton_in_car))
							.addGap(18, 18, 18)
							.addGroup(jPanel_inLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField_in_licensePlate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
							.addGap(4, 4, 4)
							.addComponent(jLabel_in_licensePlateMsg)
							.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
							.addGroup(jPanel_inLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField_in_ticketNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4))
							.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(jLabel_in_ticketMsg)
							.addGap(18, 18, 18)
							.addGroup(jPanel_inLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5)
								.addComponent(jCheckBox_priority))
							.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
							.addComponent(jButton_checkIn)
							.addGap(35, 35, 35))
				);
			}
			jPanel_container.add(jPanel_in, "card2");

			//======== jPanel_out ========
			{

				//---- jLabel6 ----
				jLabel6.setFont(new Font("Segoe UI", Font.PLAIN, 18));
				jLabel6.setText("EXIT GATE");

				//---- jLabel7 ----
				jLabel7.setText("License plate");

				//---- jLabel8 ----
				jLabel8.setText("Ticket number");

				//---- jButton_check ----
				jButton_check.setText("CHECK");
				jButton_check.addActionListener(e -> jButton_checkActionPerformed(e));

				//---- jLabel_out_licenseMsg ----
				jLabel_out_licenseMsg.setText("jLabel14");

				//---- jLabel_out_tiketMsg ----
				jLabel_out_tiketMsg.setText("jLabel14");

				GroupLayout jPanel_outLayout = new GroupLayout(jPanel_out);
				jPanel_out.setLayout(jPanel_outLayout);
				jPanel_outLayout.setHorizontalGroup(
					jPanel_outLayout.createParallelGroup()
						.addGroup(jPanel_outLayout.createSequentialGroup()
							.addGap(24, 24, 24)
							.addGroup(jPanel_outLayout.createParallelGroup()
								.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 294, GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton_check, GroupLayout.PREFERRED_SIZE, 403, GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel_outLayout.createSequentialGroup()
									.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
									.addGroup(jPanel_outLayout.createParallelGroup()
										.addComponent(jLabel_out_licenseMsg, GroupLayout.PREFERRED_SIZE, 305, GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextField_out_licensePlate, GroupLayout.PREFERRED_SIZE, 305, GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel_outLayout.createSequentialGroup()
									.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
									.addGroup(jPanel_outLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
										.addComponent(jLabel_out_tiketMsg, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jTextField_out_ticketNumber, GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))))
							.addContainerGap(30, Short.MAX_VALUE))
				);
				jPanel_outLayout.setVerticalGroup(
					jPanel_outLayout.createParallelGroup()
						.addGroup(jPanel_outLayout.createSequentialGroup()
							.addGap(24, 24, 24)
							.addComponent(jLabel6)
							.addGap(56, 56, 56)
							.addGroup(jPanel_outLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField_out_licensePlate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel7))
							.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(jLabel_out_licenseMsg)
							.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
							.addGroup(jPanel_outLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField_out_ticketNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel8))
							.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(jLabel_out_tiketMsg)
							.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
							.addComponent(jButton_check)
							.addGap(75, 75, 75))
				);
			}
			jPanel_container.add(jPanel_out, "card3");
		}

		GroupLayout contentPaneLayout = new GroupLayout(contentPane);
		contentPane.setLayout(contentPaneLayout);
		contentPaneLayout.setHorizontalGroup(
			contentPaneLayout.createParallelGroup()
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel_container, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		contentPaneLayout.setVerticalGroup(
			contentPaneLayout.createParallelGroup()
				.addGroup(contentPaneLayout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(jPanel_container, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		pack();
		setLocationRelativeTo(getOwner());

		//======== jDialog_CheckOut ========
		{
			jDialog_CheckOut.setModal(true);
			jDialog_CheckOut.setSize(new Dimension(400, 300));
			var jDialog_CheckOutContentPane = jDialog_CheckOut.getContentPane();

			//---- jButton_checkOut ----
			jButton_checkOut.setText("Check out");
			jButton_checkOut.addActionListener(e -> jButton_checkOutActionPerformed(e));

			//---- jButton_cancel ----
			jButton_cancel.setText("Cancel");
			jButton_cancel.addActionListener(e -> jButton_cancelActionPerformed(e));

			//---- jLabel2 ----
			jLabel2.setText("Licenes plate:");

			//---- jLabel9 ----
			jLabel9.setText("Ticket:");

			//---- jLabel13 ----
			jLabel13.setText("Time in");

			//---- jLabel15 ----
			jLabel15.setText("Parking fee:");

			//---- jLabel_checkOut_licenesPlate ----
			jLabel_checkOut_licenesPlate.setText("jLabel16");

			//---- jLabel_checkOut_ticket ----
			jLabel_checkOut_ticket.setText("jLabel17");

			//---- jLabel_checkOut_timeIn ----
			jLabel_checkOut_timeIn.setText("jLabel18");

			//---- jLabel_checkOut_ParkingFee ----
			jLabel_checkOut_ParkingFee.setText("jLabel20");

			GroupLayout jDialog_CheckOutContentPaneLayout = new GroupLayout(jDialog_CheckOutContentPane);
			jDialog_CheckOutContentPane.setLayout(jDialog_CheckOutContentPaneLayout);
			jDialog_CheckOutContentPaneLayout.setHorizontalGroup(
				jDialog_CheckOutContentPaneLayout.createParallelGroup()
					.addGroup(jDialog_CheckOutContentPaneLayout.createSequentialGroup()
						.addGap(46, 46, 46)
						.addGroup(jDialog_CheckOutContentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
							.addComponent(jButton_checkOut, GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
							.addComponent(jLabel13, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(jLabel15, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
						.addGroup(jDialog_CheckOutContentPaneLayout.createParallelGroup()
							.addGroup(jDialog_CheckOutContentPaneLayout.createSequentialGroup()
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
								.addGroup(jDialog_CheckOutContentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
									.addComponent(jLabel_checkOut_timeIn, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(jLabel_checkOut_licenesPlate, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(jLabel_checkOut_ticket, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(jLabel_checkOut_ParkingFee, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE))
								.addGap(46, 46, 46))
							.addGroup(jDialog_CheckOutContentPaneLayout.createSequentialGroup()
								.addGap(46, 46, 46)
								.addComponent(jButton_cancel, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
								.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
			);
			jDialog_CheckOutContentPaneLayout.setVerticalGroup(
				jDialog_CheckOutContentPaneLayout.createParallelGroup()
					.addGroup(GroupLayout.Alignment.TRAILING, jDialog_CheckOutContentPaneLayout.createSequentialGroup()
						.addContainerGap(91, Short.MAX_VALUE)
						.addGroup(jDialog_CheckOutContentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
							.addComponent(jLabel2)
							.addComponent(jLabel_checkOut_licenesPlate))
						.addGap(18, 18, 18)
						.addGroup(jDialog_CheckOutContentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
							.addComponent(jLabel9)
							.addComponent(jLabel_checkOut_ticket))
						.addGap(18, 18, 18)
						.addGroup(jDialog_CheckOutContentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
							.addComponent(jLabel13)
							.addComponent(jLabel_checkOut_timeIn))
						.addGap(18, 18, 18)
						.addGroup(jDialog_CheckOutContentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
							.addComponent(jLabel15)
							.addComponent(jLabel_checkOut_ParkingFee))
						.addGap(32, 32, 32)
						.addGroup(jDialog_CheckOutContentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
							.addComponent(jButton_checkOut)
							.addComponent(jButton_cancel))
						.addGap(37, 37, 37))
			);
		}

		//---- buttonGroup_in_vehicleType ----
		buttonGroup_in_vehicleType.add(jRadioButton_in_motorbike);
		buttonGroup_in_vehicleType.add(jRadioButton_in_bikecycle);
		buttonGroup_in_vehicleType.add(jRadioButton_in_car);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inActionPerformed
        // TODO add your handling code here:
        jPanel_in.setVisible(true);
        jPanel_out.setVisible(false);

    }//GEN-LAST:event_btn_inActionPerformed

    private void btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outActionPerformed
        // TODO add your handling code here:
        jPanel_in.setVisible(false);
        jPanel_out.setVisible(true);
    }//GEN-LAST:event_btn_outActionPerformed

    private void jButton_checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checkInActionPerformed
        // TODO add your handling code here:

        String parkingLotID;
        String ticketNum;
        String licensePlate;
	    String timeIn;
        String timeOut = "";

	    VehicleType vehicleType = null;
	    if (jRadioButton_in_bikecycle.isSelected()) {
            vehicleType = VehicleType.BICYCLE;
        }
        else if (jRadioButton_in_motorbike.isSelected()) {
            vehicleType = VehicleType.MOTORBIKE;
        }
        else if (jRadioButton_in_car.isSelected()) {
            vehicleType = VehicleType.CAR;
        }

        parkingLotID = employee.getParkingLotID();
        ticketNum = jTextField_in_ticketNumber.getText().trim();
        licensePlate = jTextField_in_licensePlate.getText().trim();
        timeIn = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy/MM/dd - HH:mm:ss"));
	    boolean priority = jCheckBox_priority.isSelected();

        //validate
        jLabel_in_licensePlateMsg.setText("");
        jLabel_in_ticketMsg.setText("");

        boolean isValid = true;
        String requiredFieldMsg = "This is a required field";
        if (licensePlate.isEmpty() && vehicleType != VehicleType.BICYCLE) {
            isValid = false;
            jLabel_in_licensePlateMsg.setText(requiredFieldMsg);
        }

        if (ticketNum.isEmpty()) {
            isValid = false;
            jLabel_in_ticketMsg.setText(requiredFieldMsg);
        }

        if (!isValid) return;

        try {
            Set<Ticket> tickets = dataAccess.TicketDataAccess.getTickets();
            Map<String, Vehicle> parkingVehicles = VehicleDataAccess.getVehicles();
            if (!tickets.contains(new Ticket(ticketNum))) {
                JOptionPane.showMessageDialog(this, "This ticket has not been assigned");
                return;
            }

            if (parkingVehicles.containsKey(ticketNum)) {
                JOptionPane.showMessageDialog(this, "This ticket was assigned to one vehicle in this lot already");
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(Frame_StaffWork.class.getName()).log(Level.SEVERE, null, ex);
        }

        //end validate
        Vehicle v = new Vehicle(parkingLotID, ticketNum, licensePlate,
                                vehicleType, timeIn, timeOut, priority);
        try {
            VehicleDataAccess.addVehicle(v);
        } catch (IOException ex) {
            Logger.getLogger(Frame_StaffWork.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(v);

    }//GEN-LAST:event_jButton_checkInActionPerformed

    private void jRadioButton_in_bikecycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_in_bikecycleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_in_bikecycleActionPerformed

    private void jRadioButton_in_bikecycleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_in_bikecycleStateChanged
        // TODO add your handling code here:
        boolean isSelected = jRadioButton_in_bikecycle.isSelected();
        jTextField_in_licensePlate.setEnabled(!isSelected);
        if (isSelected) {
            jTextField_in_licensePlate.setText("");
        }
    }//GEN-LAST:event_jRadioButton_in_bikecycleStateChanged

    private void jButton_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checkActionPerformed
        // TODO add your handling code here:
        Map<String, Vehicle> vehicles = new TreeMap<>();
        try {
            vehicles = VehicleDataAccess.getVehicles();
        } catch (Exception ex) {
            Logger.getLogger(Frame_StaffWork.class.getName()).log(Level.SEVERE, null, ex);
        }

        String ticket = jTextField_out_ticketNumber.getText().trim();
        String  licensePlate = jTextField_out_licensePlate.getText().trim();
        Vehicle v = vehicles.get(ticket);

        if (v == null) {
	        JOptionPane.showMessageDialog(this,
	                                      "No such vehicle found in this lot related to this ticket!"
	        );
	        return;
        }
        v.setTimeOut(LocalDateTime.now().format(
				DateTimeFormatter.ofPattern("yyyy/MM/dd - HH:mm:ss")));
        vehicleParkingCheckOut = v;
        if (v.getLicensePlate().compareTo(licensePlate) != 0) {
            JOptionPane.showMessageDialog(this, "Not match");
            return;
        }

        System.out.println(v);

        jLabel_checkOut_licenesPlate.setText(v.getLicensePlate());
        jLabel_checkOut_ticket.setText(v.getTicket());
        jLabel_checkOut_timeIn.setText(v.getTimeIn());

        int parkingFee = switch (v.getType()) {
	        case BICYCLE -> UnitPrice.BICYCLE.getPrice();
	        case MOTORBIKE -> UnitPrice.MOTORBIKE.getPrice();
	        case CAR -> UnitPrice.CAR.getPrice();
        };

	    if(v.isPrioritised()){
            parkingFee = 0;
        }
        jLabel_checkOut_ParkingFee.setText(String.valueOf(parkingFee));

        jDialog_CheckOut.setVisible(true);
        System.out.println(parkingFee);

    }//GEN-LAST:event_jButton_checkActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        // TODO add your handling code here:
        jDialog_CheckOut.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jButton_checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checkOutActionPerformed
        try {
            // TODO add your handling code here:
	        String lotID = jLabel_parkingLotID.getText();
	        String ticketNumber = jLabel_checkOut_ticket.getText();
	        boolean canRemoveThisVehicle =
		            VehicleDataAccess.removeVehicle(ticketNumber, lotID);
			if (!canRemoveThisVehicle) {
				JOptionPane.showMessageDialog(this,
				                              "No such vehicle in this lot " + lotID
				                              + "has ticket code of " + ticketNumber
				);
				return;
			}
            int parkingFee;
            if (vehicleParkingCheckOut.isPrioritised())
				parkingFee = 0;
			else
				parkingFee = switch (vehicleParkingCheckOut.getType()) {
					case MOTORBIKE -> UnitPrice.MOTORBIKE.getPrice();
					case BICYCLE -> UnitPrice.BICYCLE.getPrice();
					case CAR -> UnitPrice.CAR.getPrice();
				};
            dataAccess.LogDataAccess.add(new LoggedVehicle(vehicleParkingCheckOut, parkingFee));
            jTextField_out_licensePlate.setText("");
            jTextField_out_ticketNumber.setText("");
            jDialog_CheckOut.dispose();
        } catch (Exception ex) {
            Logger.getLogger(Frame_StaffWork.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_checkOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException |
                 IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_StaffWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
	    //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frame_StaffWork().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
	// Generated using JFormDesigner Evaluation license - Trường Khắc Nguyễn
	private JPanel jPanel1;
	private JButton btn_in;
	private JButton btn_out;
	private JPanel jPanel_container;
	private JPanel jPanel_in;
	private JLabel jLabel1;
	private JTextField jTextField_in_licensePlate;
	private JLabel jLabel3;
	private JTextField jTextField_in_ticketNumber;
	private JLabel jLabel4;
	private JLabel jLabel5;
	private JCheckBox jCheckBox_priority;
	private JButton jButton_checkIn;
	private JLabel jLabel10;
	private JRadioButton jRadioButton_in_motorbike;
	private JRadioButton jRadioButton_in_bikecycle;
	private JRadioButton jRadioButton_in_car;
	private JLabel jLabel11;
	private JLabel jLabel_parkingLotID;
	private JLabel jLabel12;
	private JLabel jLabel_staffName;
	private JLabel jLabel_in_licensePlateMsg;
	private JLabel jLabel_in_ticketMsg;
	private JPanel jPanel_out;
	private JLabel jLabel6;
	private JLabel jLabel7;
	private JTextField jTextField_out_licensePlate;
	private JLabel jLabel8;
	private JTextField jTextField_out_ticketNumber;
	private JButton jButton_check;
	private JLabel jLabel_out_licenseMsg;
	private JLabel jLabel_out_tiketMsg;
	private JDialog jDialog_CheckOut;
	private JButton jButton_checkOut;
	private JButton jButton_cancel;
	private JLabel jLabel2;
	private JLabel jLabel9;
	private JLabel jLabel13;
	private JLabel jLabel15;
	private JLabel jLabel_checkOut_licenesPlate;
	private JLabel jLabel_checkOut_ticket;
	private JLabel jLabel_checkOut_timeIn;
	private JLabel jLabel_checkOut_ParkingFee;
	private ButtonGroup buttonGroup_in_vehicleType;
    // End of variables declaration//GEN-END:variables
}
